### ISSUE TITLE
Credit Request

### ISSUE THREAD

**Issue by wcrasta** [broadtoad/Flight_Tracker#1]
Hi @broadtoad,

I've noticed that your project is very similar to my [SWA-Scraper](https://github.com/wcrasta/SWA-Scraper). If you agree that this is the case, I would appreciate a credit citation in the README of your project. My e-mail address is in my GitHub bio if you would like to further discuss.

Thanks.

**Comment by broadtoad** [comment]
Hi @wcrasta, 

Agreed that the concept is similar, but the project is my design and the code is entirely unique. I did look through [SWA-Scraper](https://github.com/wcrasta/SWA-Scraper) user feedback on issues/pull requests, and added some functionality as a result, so I'd be happy to list your tool as "Inspiration." 

Cheers, 
broadtoad

**Comment by wcrasta** [comment]
Thank you, I appreciate it!
