### ISSUE TITLE
One stop (same plane)

### ISSUE THREAD

**Issue by joshjohanning** [broadtoad/Flight_Tracker#3]
I don't think this tracks layover flights where the itinerary doesn't have you leaving the plane. 

Here is an example: 
The cheapest flight at this time is flight 1474, price $97.30. It has a layover in Denver but if you book this itinerary you don't leave the plane on the layover.

Command:
`flight_tracker -o MSP -d LAX -l 02/20/19 -p 98 -ft USD`

This will track the cheapest flight that isn't a one stop / same plane deal. The cheapest in that case is # 344 / 1321 which costs $101.80. The script confirms this.

When you run this command to specify your flight number, example:
`flight_tracker -o MSP -d LAX -l 02/20/19 -p 98 -ft USD -n 1474 `OR
`flight_tracker -o MSP -d LAX -l 02/20/19 -p 98 -ft USD -n 1474 1474`

This script reports the cheapest cost of the business class fare for that flight, or $487.08. 

Let me know if this is indeed a bug or if I am doing something wrong here. Thank you for your time. 

Screenshot:
![image](https://user-images.githubusercontent.com/19912012/49882124-8da4c200-fdf5-11e8-86e9-4a048bbfeee2.png)

**Comment by broadtoad** [comment]
Apologies for the late response. It should be fixed now. Please let me know if you run into anything else!

**Comment by joshjohanning** [comment]
PS: Just tested this and I can confirm it does work!
